apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-eks-k8s
  region: us-east-1

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
