apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: yourdockerhubusername/auth0-custom:latest  # Substitua pelo nome da sua imagem
          ports:
            - containerPort: 3000  # A porta exposta no Dockerfile