apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth  # Alinha com o Deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # A porta exposta no Dockerfile
  type: LoadBalancer