name: EKS Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AKIAUTMUZUBEBA3BB5US }}
          aws-secret-access-key: ${{ secrets.055x5iBA14v8A28C/n25wzI9E11GFlPihNUhNUkr }}
          aws-region: us-east-1

      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name aws-eks-k8s

      - name: Deploy to EKS
        run: |
          kubectl apply -f services/user-service/deployment.yaml
          kubectl apply -f services/user-service/service.yaml
          kubectl apply -f services/user-service/hpa.yaml
          kubectl apply -f services/book-service/deployment.yaml
          kubectl apply -f services/book-service/service.yaml
          kubectl apply -f services/book-service/hpa.yaml
          kubectl apply -f services/loan-service/deployment.yaml
          kubectl apply -f services/loan-service/service.yaml
          kubectl apply -f services/loan-service/hpa.yaml
          kubectl apply -f services/notification-service/deployment.yaml
          kubectl apply -f services/notification-service/service.yaml
          kubectl apply -f services/notification-service/hpa.yaml
          kubectl apply -f services/auth-service/deployment.yaml
          kubectl apply -f services/auth-service/service.yaml
          kubectl apply -f services/auth-service/hpa.yaml
          kubectl apply -f infra/monitoring/prometheus/prometheus-config.yaml
          kubectl apply -f infra/monitoring/prometheus/prometheus-deployment.yaml
          kubectl apply -f infra/monitoring/prometheus/prometheus-service.yaml
          kubectl apply -f infra/monitoring/grafana/grafana-deployment.yaml
          kubectl apply -f infra/monitoring/grafana/grafana-service.yaml
          kubectl apply -f infra/networking/ingress.yaml